### ISSUE TITLE
Sum percentage not working after 4.0.x update

### ISSUE THREAD

**Issue by silvergraphs** [biati-digital/alfred-calculate-anything#111]
If you have a problem with the workflow please answer the following questions.

**Are you using the latest version of the workflow?**
Yes

**Describe the bug**
Typing this → `5+5%` it works on 3.5 version, but not in 4.x.x

**To Reproduce**
1. Open Alfred '...'
1. Type a number and sum percentage → Ex: '5+15%'
2. See error (it doesn't make the calculation, it shows like a normal string or search on the web)

**Expected behavior**
Make the calculation. Example if i'm typing `5+5%` i expect `5.25` as result.

**Debug Output**
[18:20:01.088] Logging Started...
[18:20:04.031] Calculate Anything[[Script Filter](alfredpreferences:workflows%3Eworkflow%3Euser.workflow.1BCE8DFD-522C-4FF4-8E4B-90E6037709E2%3EBB2A4C00-3D9B-43BD-957F-AFF92B5A1DCB)] Queuing argument ''
[18:20:04.094] Calculate Anything[[Script Filter](alfredpreferences:workflows%3Eworkflow%3Euser.workflow.1BCE8DFD-522C-4FF4-8E4B-90E6037709E2%3EBB2A4C00-3D9B-43BD-957F-AFF92B5A1DCB)] Script with argv '(null)' finished
[18:20:04.096] ERROR: Calculate Anything[[Script Filter](alfredpreferences:workflows%3Eworkflow%3Euser.workflow.1BCE8DFD-522C-4FF4-8E4B-90E6037709E2%3EBB2A4C00-3D9B-43BD-957F-AFF92B5A1DCB)] Code 255: Fatal error: Uncaught Error: Call to undefined function Alfred\normalizer_normalize() in /Users/brunocaruso/Documents/AlfredSettings/Alfred.alfredpreferences/workflows/user.workflow.1BCE8DFD-522C-4FF4-8E4B-90E6037709E2/alfred/Alfred.php:318
Stack trace:
#0 /Users/brunocaruso/Documents/AlfredSettings/Alfred.alfredpreferences/workflows/user.workflow.1BCE8DFD-522C-4FF4-8E4B-90E6037709E2/process.php(29): Alfred\cleanQuery('5')
#1 Command line code(2): include_once('/Users/brunocar...')
#2 {main}
  thrown in /Users/brunocaruso/Documents/AlfredSettings/Alfred.alfredpreferences/workflows/user.workflow.1BCE8DFD-522C-4FF4-8E4B-90E6037709E2/alfred/Alfred.php on line 318
[18:20:04.097] ERROR: Calculate Anything[[Script Filter](alfredpreferences:workflows%3Eworkflow%3Euser.workflow.1BCE8DFD-522C-4FF4-8E4B-90E6037709E2%3EBB2A4C00-3D9B-43BD-957F-AFF92B5A1DCB)] JSON error: JSON text did not start with array or object and option to allow fragments not set. in JSON:
Fatal error: Uncaught Error: Call to undefined function Alfred\normalizer_normalize() in /Users/brunocaruso/Documents/AlfredSettings/Alfred.alfredpreferences/workflows/user.workflow.1BCE8DFD-522C-4FF4-8E4B-90E6037709E2/alfred/Alfred.php:318
Stack trace:
#0 /Users/brunocaruso/Documents/AlfredSettings/Alfred.alfredpreferences/workflows/user.workflow.1BCE8DFD-522C-4FF4-8E4B-90E6037709E2/process.php(29): Alfred\cleanQuery('5')
#1 Command line code(2): include_once('/Users/brunocar...')
#2 {main}
  thrown in /Users/brunocaruso/Documents/AlfredSettings/Alfred.alfredpreferences/workflows/user.workflow.1BCE8DFD-522C-4FF4-8E4B-90E6037709E2/alfred/Alfred.php on line 318
[18:20:04.191] Calculate Anything[[Script Filter](alfredpreferences:workflows%3Eworkflow%3Euser.workflow.1BCE8DFD-522C-4FF4-8E4B-90E6037709E2%3EBB2A4C00-3D9B-43BD-957F-AFF92B5A1DCB)] Queuing argument '+'
[18:20:04.237] Calculate Anything[[Script Filter](alfredpreferences:workflows%3Eworkflow%3Euser.workflow.1BCE8DFD-522C-4FF4-8E4B-90E6037709E2%3EBB2A4C00-3D9B-43BD-957F-AFF92B5A1DCB)] Queuing argument '+5'
[18:20:04.301] Calculate Anything[[Script Filter](alfredpreferences:workflows%3Eworkflow%3Euser.workflow.1BCE8DFD-522C-4FF4-8E4B-90E6037709E2%3EBB2A4C00-3D9B-43BD-957F-AFF92B5A1DCB)] Script with argv '(null)' finished
[18:20:04.304] ERROR: Calculate Anything[[Script Filter](alfredpreferences:workflows%3Eworkflow%3Euser.workflow.1BCE8DFD-522C-4FF4-8E4B-90E6037709E2%3EBB2A4C00-3D9B-43BD-957F-AFF92B5A1DCB)] Code 255: Fatal error: Uncaught Error: Call to undefined function Alfred\normalizer_normalize() in /Users/brunocaruso/Documents/AlfredSettings/Alfred.alfredpreferences/workflows/user.workflow.1BCE8DFD-522C-4FF4-8E4B-90E6037709E2/alfred/Alfred.php:318
Stack trace:
#0 /Users/brunocaruso/Documents/AlfredSettings/Alfred.alfredpreferences/workflows/user.workflow.1BCE8DFD-522C-4FF4-8E4B-90E6037709E2/process.php(29): Alfred\cleanQuery('5+5')
#1 Command line code(2): include_once('/Users/brunocar...')
#2 {main}
  thrown in /Users/brunocaruso/Documents/AlfredSettings/Alfred.alfredpreferences/workflows/user.workflow.1BCE8DFD-522C-4FF4-8E4B-90E6037709E2/alfred/Alfred.php on line 318
[18:20:04.305] ERROR: Calculate Anything[[Script Filter](alfredpreferences:workflows%3Eworkflow%3Euser.workflow.1BCE8DFD-522C-4FF4-8E4B-90E6037709E2%3EBB2A4C00-3D9B-43BD-957F-AFF92B5A1DCB)] JSON error: JSON text did not start with array or object and option to allow fragments not set. in JSON:
Fatal error: Uncaught Error: Call to undefined function Alfred\normalizer_normalize() in /Users/brunocaruso/Documents/AlfredSettings/Alfred.alfredpreferences/workflows/user.workflow.1BCE8DFD-522C-4FF4-8E4B-90E6037709E2/alfred/Alfred.php:318
Stack trace:
#0 /Users/brunocaruso/Documents/AlfredSettings/Alfred.alfredpreferences/workflows/user.workflow.1BCE8DFD-522C-4FF4-8E4B-90E6037709E2/process.php(29): Alfred\cleanQuery('5+5')
#1 Command line code(2): include_once('/Users/brunocar...')
#2 {main}
  thrown in /Users/brunocaruso/Documents/AlfredSettings/Alfred.alfredpreferences/workflows/user.workflow.1BCE8DFD-522C-4FF4-8E4B-90E6037709E2/alfred/Alfred.php on line 318
[18:20:04.398] Calculate Anything[[Script Filter](alfredpreferences:workflows%3Eworkflow%3Euser.workflow.1BCE8DFD-522C-4FF4-8E4B-90E6037709E2%3EBB2A4C00-3D9B-43BD-957F-AFF92B5A1DCB)] Queuing argument '+5%'
[18:20:04.464] Calculate Anything[[Script Filter](alfredpreferences:workflows%3Eworkflow%3Euser.workflow.1BCE8DFD-522C-4FF4-8E4B-90E6037709E2%3EBB2A4C00-3D9B-43BD-957F-AFF92B5A1DCB)] Script with argv '(null)' finished
[18:20:04.469] ERROR: Calculate Anything[[Script Filter](alfredpreferences:workflows%3Eworkflow%3Euser.workflow.1BCE8DFD-522C-4FF4-8E4B-90E6037709E2%3EBB2A4C00-3D9B-43BD-957F-AFF92B5A1DCB)] Code 255: Fatal error: Uncaught Error: Call to undefined function Alfred\normalizer_normalize() in /Users/brunocaruso/Documents/AlfredSettings/Alfred.alfredpreferences/workflows/user.workflow.1BCE8DFD-522C-4FF4-8E4B-90E6037709E2/alfred/Alfred.php:318
Stack trace:
#0 /Users/brunocaruso/Documents/AlfredSettings/Alfred.alfredpreferences/workflows/user.workflow.1BCE8DFD-522C-4FF4-8E4B-90E6037709E2/process.php(29): Alfred\cleanQuery('5+5%')
#1 Command line code(2): include_once('/Users/brunocar...')
#2 {main}
  thrown in /Users/brunocaruso/Documents/AlfredSettings/Alfred.alfredpreferences/workflows/user.workflow.1BCE8DFD-522C-4FF4-8E4B-90E6037709E2/alfred/Alfred.php on line 318
[18:20:04.470] ERROR: Calculate Anything[[Script Filter](alfredpreferences:workflows%3Eworkflow%3Euser.workflow.1BCE8DFD-522C-4FF4-8E4B-90E6037709E2%3EBB2A4C00-3D9B-43BD-957F-AFF92B5A1DCB)] JSON error: JSON text did not start with array or object and option to allow fragments not set. in JSON:
Fatal error: Uncaught Error: Call to undefined function Alfred\normalizer_normalize() in /Users/brunocaruso/Documents/AlfredSettings/Alfred.alfredpreferences/workflows/user.workflow.1BCE8DFD-522C-4FF4-8E4B-90E6037709E2/alfred/Alfred.php:318
Stack trace:
#0 /Users/brunocaruso/Documents/AlfredSettings/Alfred.alfredpreferences/workflows/user.workflow.1BCE8DFD-522C-4FF4-8E4B-90E6037709E2/process.php(29): Alfred\cleanQuery('5+5%')
#1 Command line code(2): include_once('/Users/brunocar...')
#2 {main}
  thrown in /Users/brunocaruso/Documents/AlfredSettings/Alfred.alfredpreferences/workflows/user.workflow.1BCE8DFD-522C-4FF4-8E4B-90E6037709E2/alfred/Alfred.php on line 318

**System information:**
 - OS: macOS 11.6.1
 - Alfred Version 5.0.1 [2067]
- PHP Version 7.3.29 

**Additional context**
macOS running on a Hackintosh (OpenCore)

**Comment by silvergraphs** [comment]
Fixed with: https://github.com/biati-digital/alfred-calculate-anything/issues/104#issuecomment-1480883978

**Comment by biati-digital** [comment]
An update has been released, you should be able to update directly from Alfred or download the latest update from the [releases page](https://github.com/biati-digital/alfred-calculate-anything/releases)
