### ISSUE TITLE
Macports / PHP81 not working

### ISSUE THREAD

**Issue by Robert-M-Muench** [biati-digital/alfred-calculate-anything#58]
Looks like PHP81 makes some problems. I am not sure if this is only CA related or if Alfred internals have some problems too.

```PHP
[16:14:00.757] Logging Started...
[16:14:06.595] Calculate Anything[Script Filter] Queuing argument ''
[16:14:06.633] Calculate Anything[Script Filter] Script with argv '' finished
[16:14:06.636] ERROR: Calculate Anything[Script Filter] Code 255: Warning: preg_match_all(): Compilation failed: unrecognised compile-time option bit(s) at offset 0 in /Users/robby/Dropbox/Alfred.alfredpreferences/workflows/user.workflow.989E62B9-BBC3-4E35-B13C-7359602320C8/alfred/Alfred.php on line 388

Fatal error: Uncaught Error: Class "Alfred\Exception" not found in /Users/robby/Dropbox/Alfred.alfredpreferences/workflows/user.workflow.989E62B9-BBC3-4E35-B13C-7359602320C8/alfred/Alfred.php:391
Stack trace:
#0 /Users/robby/Dropbox/Alfred.alfredpreferences/workflows/user.workflow.989E62B9-BBC3-4E35-B13C-7359602320C8/workflow/lib/config/configuration.php(38): Alfred\getThemeStyle()
#1 /Users/robby/Library/Caches/com.runningwithcrayons.Alfred/Workflow Scripts/D6B13C41-660C-40D9-BD0F-0B65C735DBAD(3): require_once('/Users/robby/Dr...')
#2 {main}
  thrown in /Users/robby/Dropbox/Alfred.alfredpreferences/workflows/user.workflow.989E62B9-BBC3-4E35-B13C-7359602320C8/alfred/Alfred.php on line 391
[16:14:06.637] ERROR: Calculate Anything[Script Filter] JSON error: JSON text did not start with array or object and option to allow fragments not set. around line 1, column 0. in JSON:
Warning: preg_match_all(): Compilation failed: unrecognised compile-time option bit(s) at offset 0 in /Users/robby/Dropbox/Alfred.alfredpreferences/workflows/user.workflow.989E62B9-BBC3-4E35-B13C-7359602320C8/alfred/Alfred.php on line 388

Fatal error: Uncaught Error: Class "Alfred\Exception" not found in /Users/robby/Dropbox/Alfred.alfredpreferences/workflows/user.workflow.989E62B9-BBC3-4E35-B13C-7359602320C8/alfred/Alfred.php:391
Stack trace:
#0 /Users/robby/Dropbox/Alfred.alfredpreferences/workflows/user.workflow.989E62B9-BBC3-4E35-B13C-7359602320C8/workflow/lib/config/configuration.php(38): Alfred\getThemeStyle()
#1 /Users/robby/Library/Caches/com.runningwithcrayons.Alfred/Workflow Scripts/D6B13C41-660C-40D9-BD0F-0B65C735DBAD(3): require_once('/Users/robby/Dr...')
#2 {main}
  thrown in /Users/robby/Dropbox/Alfred.alfredpreferences/workflows/user.workflow.989E62B9-BBC3-4E35-B13C-7359602320C8/alfred/Alfred.php on line 391
[16:14:14.605] Calculate Anything[Script Filter] Queuing argument ' '
[16:14:14.634] Calculate Anything[Script Filter] Script with argv ' ' finished
[16:14:14.638] ERROR: Calculate Anything[Script Filter] Code 255: Warning: preg_match_all(): Compilation failed: unrecognised compile-time option bit(s) at offset 0 in /Users/robby/Dropbox/Alfred.alfredpreferences/workflows/user.workflow.989E62B9-BBC3-4E35-B13C-7359602320C8/alfred/Alfred.php on line 388

Fatal error: Uncaught Error: Class "Alfred\Exception" not found in /Users/robby/Dropbox/Alfred.alfredpreferences/workflows/user.workflow.989E62B9-BBC3-4E35-B13C-7359602320C8/alfred/Alfred.php:391
Stack trace:
#0 /Users/robby/Dropbox/Alfred.alfredpreferences/workflows/user.workflow.989E62B9-BBC3-4E35-B13C-7359602320C8/workflow/lib/config/configuration.php(38): Alfred\getThemeStyle()
#1 /Users/robby/Library/Caches/com.runningwithcrayons.Alfred/Workflow Scripts/D6B13C41-660C-40D9-BD0F-0B65C735DBAD(3): require_once('/Users/robby/Dr...')
#2 {main}
  thrown in /Users/robby/Dropbox/Alfred.alfredpreferences/workflows/user.workflow.989E62B9-BBC3-4E35-B13C-7359602320C8/alfred/Alfred.php on line 391
```

Installing and selecting PHP74 makes everything work again:
* sudo port install php74
* sudo port select php php74
* php --version

**Comment by biati-digital** [comment]
Please try the latest version [3.3.0](https://github.com/biati-digital/alfred-calculate-anything/releases)

**Comment by biati-digital** [comment]
Closing as this should already be fixed in the latest version
